import Head from 'next/head';
import { ReactElement, useEffect, useState } from 'react';
// MUI import
import { Grid, Typography, Icon } from '@mui/material';
import Box, { BoxProps } from '@mui/material/Box';
import { styled } from '@mui/material/styles';
// Components import
import Dashboard from '../components/layouts/dashboard';
import ChartLine from '../components/base/ChartLine';
import ChartRadial from '../components/base/ChartRadial';

export const BoxBaseStretch = styled(Box)<BoxProps>(() => ({
  borderRadius: 0,
  height: '100%',
}));

export const BoxImage = styled(Box)<BoxProps>(({ theme }) => ({
  backgroundRepeat: 'no-repeat',
  backgroundPosition: 'center',
  backgroundSize: 'cover',
  color: '#fff',
  padding: theme.spacing(3),
  width: '100%',
}));

const Home = () => {
  const [materialsChangeChart, setMaterialsChangeChart] = useState({
    chart: {
      id: 'material-change-line-chart',
    },
    title: {
      text: 'Tren Pergantian Material',
    },
    xaxis: {
      categories: ['0', '1', '2', '3', '4', '5', '6', '7'],
    },
    series: [
      {
        name: 'Material Items',
        data: [20, 8, 24, 21, 30, 28, 32, 15],
      },
    ],
  });
  const [activeOdp, setActiveOdp] = useState({
    chart: {
      id: 'active-odp-radial-bar-chart',
    },
    title: {
      text: 'Most Active ODP',
    },
    series: [90, 60, 45, 32],
    labels: ['ODP-PNK-FAZ', 'ODP-MDO-FAJ', 'ODP-TIM-FF', 'ODP-PNK-FEB'],
    colors: ['#1C7EC2', '#84B5BC', '#CBBB14', '#0C848C'],
  });
  const [statusEvidence, setStatusEvidence] = useState([
    {
      title: 'Need Follow Up',
      image: "url('/base/dashboard/gradient_need.png')",
      total: 3,
    },
    {
      title: 'Evidence Available',
      image: "url('/base/dashboard/gradient_available.png')",
      total: 1,
    },
    {
      title: 'Waiting Evidence',
      image: "url('/base/dashboard/gradient_waiting.png')",
      total: 4,
    },
    {
      title: 'Invalid Evidence',
      image: "url('/base/dashboard/gradient_invalid.png')",
      total: 2,
    },
  ]);
  const [totalList, setTotalList] = useState([
    {
      title: 'Est. CAPEX',
      icon: 'attach_money_outlined',
      value: '2M',
    },
    {
      title: 'Used Material (m)',
      icon: 'add_shopping_cart',
      value: '2',
    },
    {
      title: 'Total Orders',
      icon: 'mail',
      value: 100,
    },
    {
      title: 'Approved',
      icon: 'check',
      value: '98',
    },
  ]);

  useEffect(() => {
    let series = [] as number[];
    for (let index = 0; index < 4; index++) {
      const min = Math.ceil(10);
      const max = Math.floor(100);
      series.push(Math.floor(Math.random() * (max - min) + min));
    }

    setActiveOdp({ ...activeOdp, series });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>QEREN | Dashboard</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <section>
        {/* Status content */}
        <Grid container component='article' spacing={6} alignItems='stretch'>
          {statusEvidence.map((status, index) => (
            <Grid item xs={12} sm={6} md={3} key={index}>
              <BoxBaseStretch
                boxShadow={3}
                sx={{ textAlign: 'center', borderRadius: '0 0 8px 8px' }}
              >
                <BoxImage
                  sx={{
                    backgroundImage: status.image,
                  }}
                >
                  <Typography component='p' variant='h6' fontWeight='bold'>
                    {status.title}
                  </Typography>
                </BoxImage>

                <Box sx={{ padding: { xs: 1, sm: 3 } }}>
                  <Typography
                    component='p'
                    variant='h3'
                    fontWeight='bolder'
                    fontFamily='Ramabhadra'
                    marginBottom={3}
                  >
                    {status.total}
                  </Typography>
                </Box>
              </BoxBaseStretch>
            </Grid>
          ))}
        </Grid>

        {/* Chart */}
        <Grid
          container
          component='article'
          spacing={6}
          alignItems='stretch'
          sx={{ my: 6 }}
        >
          <Grid item xs={12} md={5}>
            <BoxBaseStretch boxShadow={3} sx={{ padding: { xs: 1, sm: 3 } }}>
              <ChartRadial customOptions={activeOdp} />
            </BoxBaseStretch>
          </Grid>
          <Grid item xs={12} md={7}>
            <BoxBaseStretch boxShadow={3} sx={{ padding: { xs: 1, sm: 3 } }}>
              <ChartLine customOptions={materialsChangeChart} />
            </BoxBaseStretch>
          </Grid>
        </Grid>

        {/* Total content */}
        <Box sx={{ width: { md: '75%' }, margin: 'auto' }}>
          <Grid container component='article' spacing={6} alignItems='stretch'>
            {totalList.map((total, index) => (
              <Grid item xs={12} sm={6} md={3} key={index}>
                <BoxBaseStretch
                  boxShadow={3}
                  sx={{
                    textAlign: 'center',
                    borderRadius: '8px',
                    px: 3,
                    py: 4,
                  }}
                >
                  <Typography
                    component='span'
                    sx={{
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'center',
                      fontWeight: 'bold',
                      mb: 2,
                    }}
                  >
                    <Icon sx={{ mr: 0.5 }}>{total.icon}</Icon>
                    {total.title}
                  </Typography>

                  <Typography
                    component='span'
                    variant='h3'
                    fontWeight='bolder'
                    fontFamily='Ramabhadra'
                  >
                    {total.value}
                  </Typography>
                </BoxBaseStretch>
              </Grid>
            ))}
          </Grid>
        </Box>
      </section>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Dashboard>{page}</Dashboard>;
};

export default Home;
